### ISSUE TITLE
To squash or not to squash by default

### ISSUE THREAD

**Issue by hhorak** [sclorg/rhscl-container-ci#5]
As mentioned in https://github.com/sclorg/mariadb-container/pull/9#issuecomment-239452717, current PR testing does not squash images, while it is enabled by default, so people building them themselves will get squashed images.

Disabling squashing by default would make building faster for people building images themselves and we can squash only when building for production.

Changing the default would need a change in every image.

**Comment by praiskup** [comment]
FWIW, I wouldn't squash the image by default for random user doing 'make', just because that squashing is not docker native thing.

On the other hand, we still can have two Makefile targets, and make the squashing "additional" step.  Then, we would have 2 options for user, and we can easily choose the default.  If we can waste some processor time, I would test both variants however :) as long as we support squashed images (and because the differences are real).  To be honest, if we care about the testsuite duration, there is large space for optimization..

**Comment by omron93** [comment]
> FWIW, I wouldn't squash the image by default for random user doing 'make', just because that squashing is not docker native thing.

Agree.

@bparees @hhorak Who can decide this? Does Openshift somehow declare `developer API` or is it OK to simply change default action of `make test`.?

> On the other hand, we still can have two Makefile targets, and make the squashing "additional" step. Then, we would have 2 options for user, and we can easily choose the default.

For me only one benefit of different Makefile target for non-squashing is in connection with https://github.com/sclorg/postgresql-container/pull/138 . To leave `make test` the same (add `git submodule update --init` there) to make initialization automatic and add `make check` which would do testing without squashing and requires git submodule initialization run by user.

Without this difference I see no benefit of two targets. Adding `SKIP_SQUASH=0` (or for example `SQUASH=1`) is same IMPOV. @praiskup Or what is a benefit?

> If we can waste some processor time, I would test both variants however :) as long as we support squashed images (and because the differences are real). 

It shouldn't be a problem.

> To be honest, if we care about the testsuite duration, there is large space for optimization..

:+1:

**Comment by bparees** [comment]
> @bparees @hhorak Who can decide this? Does Openshift somehow declare developer API or is it OK to simply change default action of make test.?

i don't think there's a problem w/ changing the behavior of make test, it's not an api.

as for what the behavior should be...  it should match what we publish.  If we are publishing squashed images, we should default to testing squashed images.  If we are not publishing squashed images, we should not default to testing squashed images.

**Comment by praiskup** [comment]
> For me only one benefit of different Makefile target for non-squashing is in connection with sclorg/postgresql-container#138 . To leave make test the same (add git submodule update --init there) to make initialization automatic and add make check which would do testing without squashing and requires git submodule initialization run by user.
> Without this difference I see no benefit of two targets. Adding SKIP_SQUASH=0 (or for example SQUASH=1) is same IMPOV. @praiskup Or what is a benefit?

That is equivalent, yes, at least in the basic usecase.  I lived in Makefile world too long to rather avoid variables (because users tend to misuse them).

One slight benefit of makefile targets are dependencies ... because you can, if you hack the common.mk correctly, create the "non-squashed" image as the dependency of "squashed one".   And then you can do `make` first (non-squashed version) and `make squashed` (is very quick as you don't have to re-build the squashed image).  But yes, it is not a big issue as docker does the caching anyway.

**Comment by phracek** [comment]
This repo is not used at all. We used Testing Farm. Closing
